# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: sidebar
  product: Cerm Flows
  version: 0.5
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Installation
    output: web, pdf
    folderitems:

    - title: About the Project
      url: /index.html
      output: web, pdf
      type: homepage

    - title: Installation
      url: /installation.html
      output: web, pdf

    - title: Configuration
      url: /configuration.html
      output: web, pdf

  - title: Getting Started
    output: web, pdf
    folderitems:
      - title: 1. Accessing CERM Flows
        url: /accessing.html
        output: web, pdf
  
      - title: 2. Using the editor
        url: /using_editor.html
        output: web, pdf
        
      - title: 3. Using the Flow Gallery
        url: /gallery.html
        output: web, pdf
        
      - title: 4. Building your first flow
        url: /first_flow.html
        output: web, pdf
        
      - title: 5. Debugging Errors
        url: /debugging.html
        output: web, pdf
        
      - title: 6. Using Datasets
        url: /using_datasets.html
        output: web, pdf
        
      - title: 7. Using Magic Tags
        url: /using_magictags.html
        output: web, pdf
        
      - title: 8. Measuring Performance
        url: /performance.html
        output: web, pdf

  - title: Module Reference Guide
    output: web, pdf
    folderitems:

    - title: Timers
      url: /module_timers.html
      output: web, pdf

    - title: Flow Infrastructure
      url: /module_infrastructure.html
      output: web, pdf

    - title: Email
      url: /module_emails.html
      output: web, pdf
  - title: Magic Tag Reference Guide
    output: web, pdf
    folderitems:

    - title: Data Functions
      url: /magic_data.html
      output: web, pdf

    - title: String Functions
      url: /magic_string.html
      output: web, pdf

    - title: Date Functions
      url: /magic_date.html
      output: web, pdf
