# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: sidebar
  product: Cerm Email Engine
  version: 0.5
  folders:

  - title:
    output: pdf
    type: frontmatter
    folderitems:
    - title:
      url: /titlepage.html
      output: pdf
      type: frontmatter
    - title:
      url: /tocpage.html
      output: pdf
      type: frontmatter

  - title: Installation
    output: web, pdf
    folderitems:

    - title: About the Project
      url: /index.html
      output: web, pdf
      type: homepage

    - title: Installation
      url: /installation.html
      output: web, pdf

    - title: Configuration
      url: /configuration.html
      output: web, pdf

  - title: Getting Started
    output: web, pdf
    folderitems:
      - title: Accessing CERM Flows
        url: /accessing.html
        output: web, pdf
  
      - title: Using the editor
        url: /using_editor.html
        output: web, pdf
        
      - title: Using the Flow Gallery
        url: /gallery.html
        output: web, pdf
        
      - title: Building your first flow
        url: /first_flow.html
        output: web, pdf
        
      - title: Debugging Errors
        url: /debugging.html
        output: web, pdf
        
      - title: Measuring Performance
        url: /performance.html
        output: web, pdf

  - title: Modules
    output: web, pdf
    folderitems:

    - title: Timers
      url: /mydoc_about_ruby_gems_etc.html
      output: web, pdf

    - title: Flow Infrastructure
      url: /mydoc_install_jekyll_on_mac.html
      output: web, pdf

    - title: Email
      url: /mydoc_install_jekyll_on_windows.html
      output: web, pdf
